### ISSUE TITLE
Upgrade to latest upstream release

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/cg-deploy-prometheus#132]
https://github.com/bosh-prometheus/prometheus-boshrelease/releases - 26.2

**Comment by tammersaleh** [comment]
Maybe see the stratos pipeline for a technique for alerting on the next available release?

**Comment by bengerman13** [comment]
There's a version incompatibility here. I don't recall exactly how the incompatibility shakes out, but we can't update prometheus until we update Kubernetes (or jettison it)

**Comment by bengerman13** [comment]
from a slack convo in December:
> I finally dug into why prometheus won’t deploy in staging - I think it’s ultimately because our k8s cluster is too old
the prometheus boshrelease jumped from kube-state-metrics 1.4 to 1.8, and I think there’s an API incompatibility between kube-state-metrics 1.8 and kubernetes 1.6 (which we’re currently running)
I pinned the prometheus-boshrelease tag in Concourse, but this is yet another reason we need to ditch or upgrade k8s - we can’t have prometheus held back because k8s is crusty.

**Comment by bengerman13** [comment]
superseded by #151
